<a href="https://colab.research.google.com/github/joy9808/2026-DA1/blob/main/05w_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

# 속성 확인
s.name       # 'first'

'first'

In [2]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [3]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [4]:
s.shape

(6,)

In [5]:
s.size

6

In [6]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [7]:
s[1]

np.float64(3.0)

In [8]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [9]:
s.index = list('abcdef')
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [10]:
print(s['b'], s['d'])

3.0 nan

In [11]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [12]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [13]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [14]:
s1 = s[1:4]
s1

b    3.0
c    5.0
d    NaN
Name: first, dtype: float64

In [15]:
s1[0]

/tmp/ipykernel_13047/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(3.0)

In [16]:
s1[0] = 10
s1

/tmp/ipykernel_13047/1715506060.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0] = 10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [17]:
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [18]:
s.index = np.arange(1, 7)
s

1     1.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [19]:
s[1]

np.float64(1.0)

In [20]:
s[0]

KeyError: 0

In [21]:
s[1:3]

2    10.0
3     5.0
Name: first, dtype: float64

In [22]:
# 정수 인덱스를 새로 부여한 경우
s.index = np.arange(1, 7)
s

s[1]      # 부여된 정수 인덱스로 참조: 1.0
s[1:3]    # 슬라이싱은 0부터 시작하는 기본 인덱스 기준: 인덱스 1~2

2    10.0
3     5.0
Name: first, dtype: float64

In [23]:
import pandas as pd

age = pd.Series([9, 17, 32, 45, 65, 98], index=list('abcdef'), name='age')
age

age['b']              # 17 (단일 레이블)

np.int64(17)

In [24]:
age[[1, 3, 5]]

/tmp/ipykernel_13047/1546391730.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1, 3, 5]]

b    17
d    45
f    98
Name: age, dtype: int64

In [25]:
age[['a', 'f', 'd']]

a     9
f    98
d    45
Name: age, dtype: int64

In [26]:
age[['c']]

c    32
Name: age, dtype: int64

In [27]:
import pandas as pd

s = pd.Series([3, 6, -3, 0, -4, 8, -7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64

In [28]:
s>0

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [29]:
s % 2 == 0

0    False
1     True
2    False
3     True
4     True
5     True
6    False
dtype: bool

In [30]:
s[s > 0]

0    3
1    6
5    8
dtype: int64

In [31]:
s[~(s > 0)]

2   -3
3    0
4   -4
6   -7
dtype: int64

In [32]:
s[s%2==0]

1    6
3    0
4   -4
5    8
dtype: int64

In [33]:
s[s%2!=0]

0    3
2   -3
6   -7
dtype: int64

In [34]:
s[(s>0)&(s%2==0)]

1    6
5    8
dtype: int64

In [35]:
import numpy as np
import pandas as pd

s = ['희빈', '수영', '현수', '지호', '지민']
p = pd.Series([99, 84, 92, 65, 78], index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    78
dtype: int64

In [36]:
p.name = '수학성적'
p.index.name = 'st_name'
p

st_name
희빈    99
수영    84
현수    92
지호    65
지민    78
Name: 수학성적, dtype: int64

In [37]:
p.sort_values()

st_name
지호    65
지민    78
수영    84
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [38]:
p.sort_values(ascending=False)

st_name
희빈    99
현수    92
수영    84
지민    78
지호    65
Name: 수학성적, dtype: int64

In [39]:
p.sort_index()

st_name
수영    84
지민    78
지호    65
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [40]:
p.sort_index(ascending=False)

st_name
희빈    99
현수    92
지호    65
지민    78
수영    84
Name: 수학성적, dtype: int64

In [41]:
import numpy as np
import pandas as pd

s = ['희빈', '수영', '현수', '지호', '지민']
p = pd.Series([99, 84, 92, 65, 78], index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    78
dtype: int64

In [ ]:
print(p.max())

In [ ]:
print(p.min())

In [ ]:
print(p.mean())

In [ ]:
print(p.median())

In [ ]:
print(p.count())

In [ ]:
print(p.size)

In [ ]:
p.describe()

In [ ]:
import numpy as np
import pandas as pd

s = pd.Series([3, 1, 1, 2, None, np.nan, 4, 6, 6, np.nan])
s

In [ ]:
s.values

In [ ]:
s.count()                        # 결측값 제외 원소 수: 7

In [ ]:
s.value_counts()                 # 고유값 빈도 (NaN 제외)

In [ ]:
s.value_counts(dropna=False)     # NaN 포함

In [ ]:
import numpy as np
import pandas as pd

s = pd.Series([3, 1, 1, 2, None, np.nan, 4, 6, 6, np.nan])
s

In [ ]:
s.value_counts(sort=False, dropna=False)

In [ ]:
s.value_counts(bins=4)                          # 4구간으로 빈도 집계

In [ ]:
s.value_counts(bins=4, sort=False)              # 정렬 없이

In [ ]:
s.value_counts(bins=[0.5, 3.5, 6.5], sort=False)  # 경계 직접 지정

In [ ]:
import pandas as pd

df = pd.DataFrame([10, 20, 30, 40, 50])
df

In [ ]:
import pandas as pd

df = pd.DataFrame([[1, 2, 3], [10, 20, 30], [100, 200, 300]],index=list('abc'))
df

In [ ]:
df = pd.DataFrame([[1, 2, 3], [10, 20, 30], [100, 200, 300]],index=list('abc'), columns=['A', 'B', 'C'])
df

In [ ]:
print(df.index)
print(df.columns)

In [ ]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame(data=np.arange(12).reshape(3, 4))
df1

In [ ]:
df1 = pd.DataFrame(np.random.randint(1, 46, (5, 6)))
df1

In [ ]:
df1 = pd.DataFrame(np.random.random((5, 3)))
df1

In [ ]:
import pandas as pd

df = pd.DataFrame({'numbers': [1, 2, 3],'colors': ['red', 'white', 'blue']})
df

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df = pd.DataFrame({'국어': [82, 76, 67], '수학': [99, 87, 78]},index=['김국진', '신영희', '이길순'])
df

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
import pandas as pd

courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
courses

In [ ]:
fees = pd.Series([250000, 300000, 200000], name='fees')
fees

In [ ]:
# 방법 1: dict로 생성
df = pd.DataFrame({courses.name: courses, fees.name: fees})
df

In [ ]:
# 방법 2: concat으로 열 방향 합치기
df = pd.concat([courses, fees], axis=1)
df

In [ ]:
# 방법 3: concat 기본 (행 방향)
df = pd.concat([courses, fees])
df

In [42]:
import pandas as pd
df = pd.DataFrame([{'국어': 70, '수학': 89, '영어': 90},
                   {'국어': 80, '영어': 99},
                   {'수학': 66, '영어': 78}])
df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [43]:
s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 73, 83, 99])
s3 = pd.Series([92, 75, 82, 75])
s1

0    90
1    80
2    60
3    66
dtype: int64

In [45]:
df = pd.DataFrame({'국어': s1, '수학': s2, '영어': s3})
df

   국어  수학  영어
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [46]:
df.index = ['노', '장', '박', '강']
df

   국어  수학  영어
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [47]:
df = pd.DataFrame({'A': pd.Series([10, 20, 30], index=[0, 1, 2]),
                   'B': pd.Series([3, 2, 1], index=[1, 2, 3])})
df

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [48]:
s1 = pd.Series([90, 80, 60], index=['노', '장', '박'])
s2 = pd.Series([45, 73, 99], index=['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3},
                  index=['노', '장', '박', '강'])
df

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [49]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [50]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [51]:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [52]:
dates = pd.date_range("20250101", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [53]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [54]:
dates = pd.date_range("20250101", end='20250110')
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [55]:
dates = pd.date_range("20250101", periods=6, freq='3D')
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [56]:
dates = pd.date_range("20250101", periods=6, freq='3H')
dates

/tmp/ipykernel_13047/3819429892.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [57]:
dates = pd.date_range("20250101", periods=6, freq='W')
dates

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [58]:
dates = pd.date_range("20260101", periods=6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [59]:
dates = pd.date_range("20260101", periods=6, freq='W-TUE')
dates

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

In [60]:
dates = pd.date_range("20260101", periods=6, freq='W-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [61]:
dates = pd.date_range("20250101", periods=6, freq='M')
dates

/tmp/ipykernel_13047/746379463.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [62]:
dates = pd.date_range("20250101", periods=6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [63]:
dates = pd.date_range("20250302", periods=6)
dates

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

In [64]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-03-02 -0.053645 -0.160899  1.462711  0.273266
2025-03-03  0.018335  0.129498  0.510183  0.127061
2025-03-04 -0.876176 -1.198689  1.494336 -0.707786
2025-03-05 -0.888719 -0.873287 -0.461752 -1.302278
2025-03-06 -0.190775 -0.476652  0.145401 -1.044534
2025-03-07 -0.180704 -2.609433 -0.445681  1.067993

In [65]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})
df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [66]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

In [67]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [68]:
pf['중간']
# 또는 pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [69]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [70]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [71]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [72]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [73]:
pf['중간'] > 20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [74]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [75]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [76]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [77]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [78]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [79]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [80]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [81]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [82]:
pf.loc[(pf.중간 > 10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [83]:
pf.loc[pf.index[0]] # 첫 번째 행 검색

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [84]:
pf.loc[[pf.index[0]]] # 첫 번째 행 검색

     중간  기말  과제  출석
윤일형  25  35   8  18

In [85]:
pf.loc[pf.index[1:4]] # 슬라이싱 행 검색

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [86]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [87]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [88]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [89]:
pf.loc[:, ['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [93]:
import pandas as pd
df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [94]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [96]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [97]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [98]:
df.sum(axis = 1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [99]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [100]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [101]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [102]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [103]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [104]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [105]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [106]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [107]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [108]:
df.max(axis=None)

522

In [109]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [110]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [111]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [112]:
df.min(axis=None)

4

In [113]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [114]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [115]:
df2 = df.copy()
df2['재해지수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [116]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해지수     4997
dtype: int64

In [117]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [118]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [119]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [120]:
df2[ [True]*6 + [False]*7 ]

         사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [121]:
df2['재해지수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해지수, dtype: bool

In [122]:
df2[df2['재해지수'] > 400]

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [123]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [124]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [125]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [126]:
df[df['사망(명)'].isin([7, 10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [127]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350) ]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [128]:
df[ df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [129]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [130]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [131]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [132]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [133]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [137]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [138]:
df.query('A > 0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [139]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [140]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

16p부터 ㄱ