<a href="https://colab.research.google.com/github/joy9808/2026-DA1/blob/main/05w_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

# 속성 확인
s.name       # 'first'

'first'

In [3]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [4]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [6]:
s.shape

(6,)

In [7]:
s.size

6

In [15]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [16]:
s[1]

np.float64(3.0)

In [17]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [22]:
s.index = list('abcdef')
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [23]:
print(s['b'], s['d'])

3.0 nan

In [24]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [25]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [26]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [27]:
s1 = s[1:4]
s1

b    3.0
c    5.0
d    NaN
Name: first, dtype: float64

In [28]:
s1[0]

/tmp/ipykernel_2748/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(3.0)

In [29]:
s1[0] = 10
s1

/tmp/ipykernel_2748/1715506060.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0] = 10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [30]:
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [31]:
s.index = np.arange(1, 7)
s

1     1.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [32]:
s[1]

np.float64(1.0)

In [33]:
s[0]

KeyError: 0

In [34]:
s[1:3]

2    10.0
3     5.0
Name: first, dtype: float64

In [9]:
# 정수 인덱스를 새로 부여한 경우
s.index = np.arange(1, 7)
s

s[1]      # 부여된 정수 인덱스로 참조: 1.0
s[1:3]    # 슬라이싱은 0부터 시작하는 기본 인덱스 기준: 인덱스 1~2

2    10.0
3     5.0
Name: first, dtype: float64

In [11]:
import pandas as pd

age = pd.Series([9, 17, 32, 45, 65, 98], index=list('abcdef'), name='age')
age

age['b']              # 17 (단일 레이블)

np.int64(17)

In [12]:
age[[1, 3, 5]]

/tmp/ipykernel_2748/1546391730.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1, 3, 5]]

b    17
d    45
f    98
Name: age, dtype: int64

In [13]:
age[['a', 'f', 'd']]

a     9
f    98
d    45
Name: age, dtype: int64

In [14]:
age[['c']]

c    32
Name: age, dtype: int64

In [35]:
import pandas as pd

s = pd.Series([3, 6, -3, 0, -4, 8, -7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64

In [36]:
s>0

0     True
1     True
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [37]:
s % 2 == 0

0    False
1     True
2    False
3     True
4     True
5     True
6    False
dtype: bool

In [38]:
s[s > 0]

0    3
1    6
5    8
dtype: int64

In [39]:
s[~(s > 0)]

2   -3
3    0
4   -4
6   -7
dtype: int64

In [40]:
s[s%2==0]

1    6
3    0
4   -4
5    8
dtype: int64

In [41]:
s[s%2!=0]

0    3
2   -3
6   -7
dtype: int64

In [42]:
s[(s>0)&(s%2==0)]

1    6
5    8
dtype: int64

In [43]:
import numpy as np
import pandas as pd

s = ['희빈', '수영', '현수', '지호', '지민']
p = pd.Series([99, 84, 92, 65, 78], index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    78
dtype: int64

In [44]:
p.name = '수학성적'
p.index.name = 'st_name'
p

st_name
희빈    99
수영    84
현수    92
지호    65
지민    78
Name: 수학성적, dtype: int64

In [45]:
p.sort_values()

st_name
지호    65
지민    78
수영    84
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [46]:
p.sort_values(ascending=False)

st_name
희빈    99
현수    92
수영    84
지민    78
지호    65
Name: 수학성적, dtype: int64

In [47]:
p.sort_index()

st_name
수영    84
지민    78
지호    65
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [48]:
p.sort_index(ascending=False)

st_name
희빈    99
현수    92
지호    65
지민    78
수영    84
Name: 수학성적, dtype: int64

In [49]:
import numpy as np
import pandas as pd

s = ['희빈', '수영', '현수', '지호', '지민']
p = pd.Series([99, 84, 92, 65, 78], index=s)
p

희빈    99
수영    84
현수    92
지호    65
지민    78
dtype: int64

In [50]:
print(p.max())

99

In [51]:
print(p.min())

65

In [52]:
print(p.mean())

83.6

In [53]:
print(p.median())

84.0

In [54]:
print(p.count())

5

In [55]:
print(p.size)

5

In [56]:
p.describe()

count     5.000000
mean     83.600000
std      13.088163
min      65.000000
25%      78.000000
50%      84.000000
75%      92.000000
max      99.000000
dtype: float64

In [57]:
import numpy as np
import pandas as pd

s = pd.Series([3, 1, 1, 2, None, np.nan, 4, 6, 6, np.nan])
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [58]:
s.values

array([ 3.,  1.,  1.,  2., nan, nan,  4.,  6.,  6., nan])

In [59]:
s.count()                        # 결측값 제외 원소 수: 7

np.int64(7)

In [60]:
s.value_counts()                 # 고유값 빈도 (NaN 제외)

1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [61]:
s.value_counts(dropna=False)     # NaN 포함

NaN    3
1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [62]:
import numpy as np
import pandas as pd

s = pd.Series([3, 1, 1, 2, None, np.nan, 4, 6, 6, np.nan])
s

0    3.0
1    1.0
2    1.0
3    2.0
4    NaN
5    NaN
6    4.0
7    6.0
8    6.0
9    NaN
dtype: float64

In [63]:
s.value_counts(sort=False, dropna=False)

3.0    1
1.0    2
2.0    1
NaN    3
4.0    1
6.0    2
Name: count, dtype: int64

In [64]:
s.value_counts(bins=4)                          # 4구간으로 빈도 집계

(0.994, 2.25]    3
(4.75, 6.0]      2
(2.25, 3.5]      1
(3.5, 4.75]      1
Name: count, dtype: int64

In [65]:
s.value_counts(bins=4, sort=False)              # 정렬 없이

(0.994, 2.25]    3
(2.25, 3.5]      1
(3.5, 4.75]      1
(4.75, 6.0]      2
Name: count, dtype: int64

In [66]:
s.value_counts(bins=[0.5, 3.5, 6.5], sort=False)  # 경계 직접 지정

(0.499, 3.5]    4
(3.5, 6.5]      3
Name: count, dtype: int64

In [68]:
import pandas as pd

df = pd.DataFrame([10, 20, 30, 40, 50])
df

    0
0  10
1  20
2  30
3  40
4  50

In [69]:
import pandas as pd

df = pd.DataFrame([[1, 2, 3], [10, 20, 30], [100, 200, 300]],index=list('abc'))
df

     0    1    2
a    1    2    3
b   10   20   30
c  100  200  300

In [70]:
df = pd.DataFrame([[1, 2, 3], [10, 20, 30], [100, 200, 300]],index=list('abc'), columns=['A', 'B', 'C'])
df

     A    B    C
a    1    2    3
b   10   20   30
c  100  200  300

In [71]:
print(df.index)
print(df.columns)

Index(['a', 'b', 'c'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')

In [72]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame(data=np.arange(12).reshape(3, 4))
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [73]:
df1 = pd.DataFrame(np.random.randint(1, 46, (5, 6)))
df1

    0   1   2   3   4   5
0  35  45  28   8  25   2
1  43  36  36   6  43  19
2  29   3   7  25  40  23
3  33  44   8  14  24   1
4   9  23  21  24  44  24

In [74]:
df1 = pd.DataFrame(np.random.random((5, 3)))
df1

          0         1         2
0  0.598233  0.088299  0.321040
1  0.839190  0.340134  0.685855
2  0.165267  0.339024  0.446165
3  0.112749  0.364478  0.002563
4  0.024863  0.397711  0.242385

In [75]:
import pandas as pd

df = pd.DataFrame({'numbers': [1, 2, 3],'colors': ['red', 'white', 'blue']})
df

   numbers colors
0        1    red
1        2  white
2        3   blue

In [76]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [77]:
df.columns

Index(['numbers', 'colors'], dtype='object')

In [78]:
df = pd.DataFrame({'국어': [82, 76, 67], '수학': [99, 87, 78]},index=['김국진', '신영희', '이길순'])
df

     국어  수학
김국진  82  99
신영희  76  87
이길순  67  78

In [79]:
df.index

Index(['김국진', '신영희', '이길순'], dtype='object')

In [80]:
df.columns

Index(['국어', '수학'], dtype='object')

In [81]:
import pandas as pd

courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
courses

0      Spark
1    PySpark
2     Hadoop
Name: courses, dtype: object

In [82]:
fees = pd.Series([250000, 300000, 200000], name='fees')
fees

0    250000
1    300000
2    200000
Name: fees, dtype: int64

In [83]:
# 방법 1: dict로 생성
df = pd.DataFrame({courses.name: courses, fees.name: fees})
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [84]:
# 방법 2: concat으로 열 방향 합치기
df = pd.concat([courses, fees], axis=1)
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [85]:
# 방법 3: concat 기본 (행 방향)
df = pd.concat([courses, fees])
df

0      Spark
1    PySpark
2     Hadoop
0     250000
1     300000
2     200000
dtype: object